server:
  port: 13000
  servlet:
    session:
      timeout: 30m
spring:
  session:
    store-type: redis
  application:
    name: auth-server
  cloud:
    nacos:
      server-addr: localhost:8848
  cache:
    type: redis
    redis:
      time-to-live: 3600000 # 1h
      cache-null-values: true