server:
  port: 10000
spring:
  application:
    name: product
  cloud:
    nacos:
      server-addr: localhost:8848
  datasource:
    username: root
    password: root
    url: jdbc:mysql://172.21.9.226:3306/gulimall_pms
    driver-class-name: com.mysql.cj.jdbc.Driver
mybatis-plus:
  mapper-locations: classpath*:/mapper/**/*.xml
  global-config:
    db-config:
      id-type: auto    # 配置自增主键